name: Build MacOS APP for Ghidra

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Get the release tag
      - name: Set release tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build x86_64
        run: ./build.bash -a x86_64 -f

      - name: Build arm64
        run: ./build.bash -a arm64 -f

      - name: Package DMGs
        run: |
          mkdir -p dist
          hdiutil create dist/Ghidra-${RELEASE_TAG}-x86_64.dmg \
            -volname "Ghidra" \
            -srcfolder Ghidra.app \
            -ov \
            -format UDZO
          hdiutil create dist/Ghidra-${RELEASE_TAG}-arm64.dmg \
            -volname "Ghidra" \
            -srcfolder Ghidra.app \
            -ov \
            -format UDZO

      - name: Upload DMGs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Ghidra-${RELEASE_TAG}-x86_64.dmg
            dist/Ghidra-${RELEASE_TAG}-arm64.dmg
          token: ${{ secrets.GH_PAT }}
